#!/bin/bash
red="\e[31m"
lime="\x1b[38;5;10m"
yellow="\x1b[38;5;11m"
white="\x1b[38;5;15m"
blue="\x1b[38;5;12m"
index="index"
idx="idx"
desp=0 #desplazamiento
opcion=""

while true; do
    clear
    echo -e "${yellow}Bloc de Notas"
    echo -e "${yellow}----------------"
    echo -e "${white}Teclas de navegación:"
    echo -e "${red}  s: ${white}Desplazarse 5 notas abajo"
    echo -e "${red}  w: ${white}Desplazarse 5 notas arriba"
    echo -e "${red}  i: ${white}Empezar a escribir el nombre de la nota"
    echo -e "${red}  x: ${white}Salir"
    echo -e " \n ${blue}Notas: ${white}\n"

    #primeras 5 de idx
    if [[ ! -f $idx ]]; then
        echo "No existen notas."
    else
        tail -n +$((desp + 1)) "$idx" | head -n 5
    fi
    echo
    echo -e "${yellow}Seleccione una opcion: ${white}"

    read -n1 opcion

    case $opcion in
        s) #5 abajo
            desp=$((desp + 5))
            if [[ $desp -ge $(wc -l < "$idx") ]]; then #desp >= lineas idx
                desp=0
            fi
            ;;
        w) #5 arriba
            desp=$((desp - 5))
            if [[ $desp -lt 0 ]]; then #si desp<0
                desp=0
            fi
            ;;
        i)
                echo
                echo -n "Escriba el nombre de la nota: "
                read nombre

                # la nota existe?
                if grep -q "^$nombre -" "$idx"; then
                        echo " "
                        echo -e "${yellow}Que accion quiere realizar?"
                        echo -e "${blue}  o: Abrir nota"
                        echo -e "${red}  d: Eliminar nota"
                        read -n 1 op # guarda la accion
                        echo

                        if [[ $op == "o" ]]; then
                        I_linea=$(grep -n "^$nombre$" "$index" | cut -d: -f1)
                        if [[ -n $I_linea ]]; then
                                echo
                                echo -e "${blue}Contenido de la nota:${white}"
                                echo
                                grep -A 3 "^$nombre$" "$index"
                        else
                                echo
                                echo -e "${red}Nota no encontrada.${white}"
                        fi
                        elif [[ $op == "d" ]]; then
                        ./eliminar "$nombre"
                        if [[ $? -eq 0 ]]; then
                                echo -e "${lime}Se elimino correctamente la nota"
                        else
                                echo -e "${red}Error al eliminar la nota"
                        fi
                        else
                        echo -e "${red}Accion no valida"
                        fi
                else
                        echo -e "${red}La nota '$nombre' no se encontro.${white}"
                fi
                ;;
        x) #Salir
            echo
            echo -e "${yellow}Saliendo del bloc de notas."
            break
            ;;
        *) # Opcion valida
            echo
            echo -e "${yellow}Tecla no valida, Intentelo de nuevo.\n${white}"
            ;;
    esac

    echo
    echo -e "Presione cualquier tecla para continuar..."
    read -n1
done
